### ISSUE TITLE
zorro error

### ISSUE THREAD

**Issue by nick-youngblut** [kbseah/phylogenomics-tools#7]
I'm using zorro installed from bioconda: `zorro    2011.12.01    h14c3975_0    bioconda`, and I'm getting the following error:

```
error: Cannot create tree from alignment
 Check FastTree installation
  exiting...
```

...even though fasttree is installed. My entire conda env:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
barrnap                   0.9                           3    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
fasttree                  2.1.10               h14c3975_3    bioconda
hmmer                     3.3                  he1b5a44_0    bioconda
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
mafft                     7.455                h516909a_0    bioconda
perl                      5.26.2            h516909a_1006    conda-forge
raxml                     8.2.12               h14c3975_1    bioconda
xz                        5.2.4             h516909a_1002    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zorro                     2011.12.01           h14c3975_0    bioconda
```

Any idea what zorro isn't working?

**Comment by kbseah** [comment]
Hi Nick,

Zorro is bundled with FastTree 1.0.1, and I suspect that installing both Zorro and FastTree in a Conda env may be the source of the problem, but I haven't tested it yet. My initial hunch was that the name of the FastTree executable has changed, but both `fasttree` and `FastTree` work. Zorro also hasn't been updated since 2011.

To be honest I haven't updated or used these scripts substantially in a long time. I think that the ETE3 toolkit http://etetoolkit.org might be a more versatile alternative to explore, if you are setting up a phylogenomics workflow. 

Hope that this helps!
Brandon

**Comment by nick-youngblut** [comment]
Thanks! Yeah, I think zorro is getting too old
